# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosAp
  pod 'PurchasesHybridCommonUI', '13.37.0'
  pod 'Google-Mobile-Ads-SDK', '11.13.0'


end
